# DigitalOcean App Platform spec for siloq-backend (Django).
# 1. Replace YOUR_ORG/siloq with your GitHub repo (e.g. yourusername/siloq).
# 2. If the backend lives in a subdirectory, set source_dir to that path (e.g. siloq-backend).
# 3. Add SECRET_KEY and other env vars in the DO dashboard; link the database so DATABASE_URL is set.
# 4. Deploy: connect repo in DO and push, or: doctl apps create --spec .do/app.yaml

name: siloq-backend
region: nyc

services:
  - name: web
    github:
      repo: YOUR_ORG/siloq
      branch: main
      deploy_on_push: true
    source_dir: siloq-backend
    build_command: pip install -r requirements.txt && python manage.py collectstatic --noinput
    run_command: gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT siloq_backend.wsgi:application
    envs:
      - key: SECRET_KEY
        value: "CHANGE_ME_STRONG_SECRET"
        type: SECRET
      - key: DEBUG
        value: "False"
        scope: RUN_TIME
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME
      - key: CORS_ALLOWED_ORIGINS_EXTRA
        value: "https://siloq.ai,https://www.siloq.ai"
        scope: RUN_TIME
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: YOUR_ORG/siloq
      branch: main
      deploy_on_push: true
    source_dir: siloq-backend
    run_command: python manage.py migrate --noinput
    envs:
      - key: SECRET_KEY
        value: "CHANGE_ME_STRONG_SECRET"
        type: SECRET
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
        scope: RUN_TIME

databases:
  - name: db
    engine: PG
    version: "15"
