# Generated by Django 5.0.1 on 2026-02-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(blank=True, default='free', max_length=50),
        ),
    ]
