# Generated by Django 5.0.1 on 2026-02-15 22:16

from django.db import migrations, models


def add_subscription_status_if_missing(apps, schema_editor):
    """Only add the column if it doesn't already exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'users' AND column_name = 'subscription_status'"
        )
        if not cursor.fetchone():
            cursor.execute(
                "ALTER TABLE users ADD COLUMN subscription_status varchar(50) DEFAULT 'free' NOT NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_subscription_status_if_missing, migrations.RunPython.noop),
    ]
