# Generated by Django 5.0.1 on 2026-02-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan')], default='full', max_length=50)),
                ('url', models.URLField(help_text='URL being scanned')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, help_text='Overall SEO score (0-100)', null=True)),
                ('pages_analyzed', models.IntegerField(default=0)),
                ('scan_duration_seconds', models.FloatField(blank=True, null=True)),
                ('results', models.JSONField(default=dict, help_text='Detailed scan results including scores, issues, recommendations')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='sites.site')),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='scans_status_6c85cd_idx'), models.Index(fields=['url'], name='scans_url_0e7a23_idx')],
            },
        ),
    ]
