# Generated by Django 5.0.1 on 2026-02-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('sites', '0003_business_profile_onboarding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='scan',
            name='scans_status_6c85cd_idx',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='created_at',
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status', 'started_at'], name='scans_status_3351df_idx'),
        ),
    ]
