# Generated by Django 5.0.1 on 2026-02-15 22:16

from django.db import migrations, models


def safe_remove_created_at(apps, schema_editor):
    """Remove created_at only if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'scans' AND column_name = 'created_at'"
        )
        if cursor.fetchone():
            cursor.execute("ALTER TABLE scans DROP COLUMN created_at")


def safe_drop_index(apps, schema_editor):
    """Drop old index only if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT indexname FROM pg_indexes WHERE indexname = 'scans_status_6c85cd_idx'"
        )
        if cursor.fetchone():
            cursor.execute("DROP INDEX scans_status_6c85cd_idx")


def safe_create_index(apps, schema_editor):
    """Create new index only if it doesn't exist."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT indexname FROM pg_indexes WHERE indexname = 'scans_status_3351df_idx'"
        )
        if not cursor.fetchone():
            cursor.execute(
                "CREATE INDEX scans_status_3351df_idx ON scans (status, started_at)"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('sites', '0005_site_gsc_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-started_at']},
        ),
        migrations.RunPython(safe_drop_index, migrations.RunPython.noop),
        migrations.RunPython(safe_remove_created_at, migrations.RunPython.noop),
        migrations.RunPython(safe_create_index, migrations.RunPython.noop),
    ]
