# Generated by Django 5.0.1 on 2026-02-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_post_id', models.IntegerField(help_text='WordPress post/page ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('content', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('publish', 'Published'), ('draft', 'Draft'), ('private', 'Private')], default='publish', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('yoast_title', models.CharField(blank=True, max_length=500)),
                ('yoast_description', models.TextField(blank=True)),
                ('featured_image', models.URLField(blank=True)),
                ('siloq_page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.site')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('h1_count', models.IntegerField(default=0)),
                ('h1_text', models.CharField(blank=True, max_length=500)),
                ('h2_count', models.IntegerField(default=0)),
                ('h2_texts', models.JSONField(default=list, help_text='List of H2 headings')),
                ('h3_count', models.IntegerField(default=0)),
                ('h3_texts', models.JSONField(default=list, help_text='List of H3 headings')),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('internal_links', models.JSONField(default=list, help_text='List of internal link URLs')),
                ('external_links', models.JSONField(default=list, help_text='List of external link URLs')),
                ('images_count', models.IntegerField(default=0)),
                ('images_without_alt', models.IntegerField(default=0)),
                ('images', models.JSONField(default=list, help_text='List of image URLs and alt texts')),
                ('word_count', models.IntegerField(default=0)),
                ('reading_time_minutes', models.FloatField(default=0)),
                ('seo_score', models.IntegerField(default=0, help_text='Overall SEO score (0-100)')),
                ('issues', models.JSONField(default=list, help_text="List of SEO issues found, e.g. [{'type': 'missing_meta_description', 'severity': 'high', 'message': '...'}]")),
                ('recommendations', models.JSONField(default=list, help_text='List of SEO recommendations')),
                ('has_canonical', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True)),
                ('has_schema', models.BooleanField(default=False)),
                ('schema_type', models.CharField(blank=True, max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_version', models.CharField(default='1.0', max_length=50)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_data', to='seo.page')),
            ],
            options={
                'db_table': 'seo_data',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['site', 'status'], name='pages_site_id_e97a01_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['url'], name='pages_url_f5ef97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'wp_post_id')},
        ),
    ]
