# Generated by Django 5.0.1 on 2026-02-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_internal_links'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_e1c924_idx',
            old_name='internal_links_site_source_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_7e2254_idx',
            old_name='internal_links_site_target_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_anchor__14ddb9_idx',
            old_name='internal_links_anchor_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_mone_525ba2_idx',
            old_name='pages_is_mone_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_home_afbfd5_idx',
            old_name='pages_is_home_idx',
        ),
    ]
