# Generated by Django 5.0.1 on 2026-02-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_page_post_type'),
        ('sites', '0005_site_gsc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gsc_connected', models.BooleanField(default=False, help_text='Was GSC data available for this run?')),
                ('gsc_date_start', models.DateField(blank=True, null=True)),
                ('gsc_date_end', models.DateField(blank=True, null=True)),
                ('total_pages_analyzed', models.IntegerField(default=0)),
                ('total_clusters_found', models.IntegerField(default=0)),
                ('search_conflict_count', models.IntegerField(default=0, help_text='SEARCH_CONFLICT bucket count')),
                ('site_duplication_count', models.IntegerField(default=0, help_text='SITE_DUPLICATION bucket count')),
                ('wrong_winner_count', models.IntegerField(default=0, help_text='WRONG_WINNER bucket count')),
                ('confirmed_count', models.IntegerField(default=0, help_text='GSC-confirmed conflicts')),
                ('potential_count', models.IntegerField(default=0, help_text='Static detection (not GSC-validated)')),
                ('wrong_winner_badge_count', models.IntegerField(default=0, help_text='Wrong winner detections')),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cannibalization_analysis_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_key', models.CharField(help_text='Unique key for grouping (conflict_type:keyword)', max_length=500)),
                ('bucket', models.CharField(choices=[('SEARCH_CONFLICT', 'Search Conflict'), ('SITE_DUPLICATION', 'Site Duplication'), ('WRONG_WINNER', 'Wrong Winner')], max_length=50)),
                ('badge', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('POTENTIAL', 'Potential'), ('WRONG_WINNER', 'Wrong Winner')], max_length=50)),
                ('conflict_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('SEVERE', 'Severe'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('action_code', models.CharField(max_length=100)),
                ('priority_score', models.IntegerField(default=0, help_text='Calculated priority: bucket(50) + severity(30) + impressions(20)')),
                ('page_count', models.IntegerField(default=0)),
                ('pages_json', models.JSONField(default=list, help_text='List of page objects with URL, title, type, etc.')),
                ('gsc_query', models.CharField(blank=True, help_text='Search query triggering conflict', max_length=500)),
                ('gsc_total_impressions', models.IntegerField(default=0, help_text='Total impressions across all pages')),
                ('gsc_total_clicks', models.IntegerField(default=0, help_text='Total clicks across all pages')),
                ('gsc_data_json', models.JSONField(default=dict, help_text='Full GSC data: impression shares, positions, etc.')),
                ('recommendation', models.TextField(blank=True)),
                ('suggested_canonical_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cannibalization_clusters',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('silo_id', models.IntegerField(blank=True, help_text='Silo/money page this belongs to', null=True)),
                ('page_type', models.CharField(choices=[('hub', 'Hub/Money Page'), ('spoke', 'Spoke/Supporting Page'), ('product', 'Product Page'), ('category', 'Category Page'), ('blog', 'Blog Post'), ('homepage', 'Homepage'), ('general', 'General')], default='general', max_length=50)),
                ('assignment_source', models.CharField(choices=[('auto_bootstrap', 'Auto-detected during bootstrap'), ('auto_analysis', 'Auto-detected during analysis'), ('manual', 'Manually assigned by user'), ('content_generation', 'Assigned during content generation')], default='auto_bootstrap', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('reassigned', 'Reassigned')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyword_assignments',
            },
        ),
        migrations.CreateModel(
            name='PageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(help_text='Reference to Page.id')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('normalized_url', models.CharField(max_length=1000)),
                ('normalized_path', models.CharField(max_length=1000)),
                ('classified_type', models.CharField(help_text='homepage, location, blog, product, category_woo, shop_root, etc.', max_length=50)),
                ('is_legacy_variant', models.BooleanField(default=False)),
                ('folder_root', models.CharField(blank=True, max_length=100)),
                ('parent_path', models.CharField(blank=True, max_length=1000)),
                ('slug_last', models.CharField(blank=True, max_length=500)),
                ('depth', models.IntegerField(default=0)),
                ('geo_node', models.CharField(blank=True, max_length=200)),
                ('service_keyword', models.CharField(blank=True, max_length=200)),
                ('slug_tokens_json', models.JSONField(default=list, help_text='List of slug tokens for similarity comparison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cannibalization_page_classifications',
                'ordering': ['classified_type', 'normalized_path'],
            },
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_e1c924_idx',
            old_name='internal_links_site_source_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_site_id_7e2254_idx',
            old_name='internal_links_site_target_idx',
        ),
        migrations.RenameIndex(
            model_name='internallink',
            new_name='internal_li_anchor__14ddb9_idx',
            old_name='internal_links_anchor_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_mone_525ba2_idx',
            old_name='pages_is_mone_idx',
        ),
        migrations.RenameIndex(
            model_name='page',
            new_name='pages_is_home_afbfd5_idx',
            old_name='pages_is_home_idx',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cannibalization_runs', to='sites.site'),
        ),
        migrations.AddField(
            model_name='clusterresult',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='seo.analysisrun'),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_assignments', to='seo.page'),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='reassigned_from_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_keywords', to='seo.page'),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_assignments', to='sites.site'),
        ),
        migrations.AddField(
            model_name='pageclassification',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_classifications', to='seo.analysisrun'),
        ),
        migrations.AddField(
            model_name='pageclassification',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_classifications', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['site', '-started_at'], name='cannibaliza_site_id_ae22c5_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='cannibaliza_status_460f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterresult',
            index=models.Index(fields=['analysis_run', '-priority_score'], name='cannibaliza_analysi_6f5e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterresult',
            index=models.Index(fields=['bucket'], name='cannibaliza_bucket_e80591_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterresult',
            index=models.Index(fields=['badge'], name='cannibaliza_badge_244f71_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterresult',
            index=models.Index(fields=['status'], name='cannibaliza_status_775e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterresult',
            index=models.Index(fields=['cluster_key'], name='cannibaliza_cluster_352043_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['site', 'status'], name='keyword_ass_site_id_faf62c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['page', 'status'], name='keyword_ass_page_id_e149c6_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['silo_id'], name='keyword_ass_silo_id_1e32aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordassignment',
            unique_together={('keyword', 'site_id')},
        ),
        migrations.AddIndex(
            model_name='pageclassification',
            index=models.Index(fields=['analysis_run', 'classified_type'], name='cannibaliza_analysi_2f61ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pageclassification',
            index=models.Index(fields=['site', 'analysis_run'], name='cannibaliza_site_id_aeb10c_idx'),
        ),
        migrations.AddIndex(
            model_name='pageclassification',
            index=models.Index(fields=['folder_root'], name='cannibaliza_folder__7732cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pageclassification',
            index=models.Index(fields=['is_legacy_variant'], name='cannibaliza_is_lega_ee0ae4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageclassification',
            unique_together={('analysis_run', 'page_id')},
        ),
    ]
