# Generated by Django 5.0.1 on 2026-02-15 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_keyword_assignment'),
        ('sites', '0005_site_gsc_fields'),
    ]

    operations = [
        # ─────────────────────────────────────────────────────
        # NEW TABLES: Core Registry
        # ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='SiloDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('hub_page_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('hub_page_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'silo_definitions',
            },
        ),
        migrations.CreateModel(
            name='SiloKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=500)),
                ('keyword_type', models.CharField(default='supporting', max_length=20)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'silo_keywords',
            },
        ),
        migrations.CreateModel(
            name='KeywordAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=500)),
                ('previous_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('new_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('previous_page_type', models.CharField(blank=True, max_length=30, null=True)),
                ('new_page_type', models.CharField(blank=True, max_length=30, null=True)),
                ('action', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'keyword_assignment_history',
            },
        ),
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=2048)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('post_type', models.CharField(blank=True, max_length=50, null=True)),
                ('taxonomy', models.CharField(blank=True, max_length=100, null=True)),
                ('term_id', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('title_tag', models.CharField(blank=True, max_length=500, null=True)),
                ('h1_tag', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('canonical_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('redirect_target', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_indexable', models.BooleanField(default=True)),
                ('noindex_source', models.CharField(blank=True, max_length=50, null=True)),
                ('has_canonical_self', models.BooleanField(default=True)),
                ('canonical_points_to', models.CharField(blank=True, max_length=2048, null=True)),
                ('url_depth', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('has_schema_markup', models.BooleanField(default=False)),
                ('internal_links_in', models.IntegerField(default=0)),
                ('internal_links_out', models.IntegerField(default=0)),
                ('backlink_count', models.IntegerField(default=0)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page_metadata',
            },
        ),

        # ─────────────────────────────────────────────────────
        # NEW TABLES: Detection & Conflicts
        # ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='CannibalizationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=500)),
                ('conflict_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('raw_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('adjusted_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('semantic_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('gsc_query_overlap_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('intent_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('impression_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('status', models.CharField(default='open', max_length=30)),
                ('resolution_type', models.CharField(blank=True, max_length=30, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detection_source', models.CharField(default='pipeline', max_length=30)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('max_impressions', models.IntegerField(default=0)),
                ('shared_gsc_queries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cannibalization_conflicts',
            },
        ),
        migrations.CreateModel(
            name='ConflictPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=2048)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('page_type', models.CharField(blank=True, max_length=30, null=True)),
                ('gsc_impressions', models.IntegerField(default=0)),
                ('gsc_clicks', models.IntegerField(default=0)),
                ('gsc_avg_position', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('backlink_count', models.IntegerField(default=0)),
                ('is_recommended_winner', models.BooleanField(default=False)),
                ('winner_score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_indexable', models.BooleanField(default=True)),
                ('http_status', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conflict_pages',
            },
        ),

        # RedirectRegistry MUST be created before ConflictResolution (FK dependency)
        migrations.CreateModel(
            name='RedirectRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.CharField(max_length=2048)),
                ('target_url', models.CharField(max_length=2048)),
                ('redirect_type', models.IntegerField(default=301)),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=30, null=True)),
                ('chain_depth', models.IntegerField(default=0)),
                ('final_destination', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_hit', models.DateTimeField(blank=True, null=True)),
                ('total_hits', models.IntegerField(default=0)),
                ('created_by', models.CharField(default='siloq_system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'redirect_registry',
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=30)),
                ('winner_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('loser_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('redirect_type', models.IntegerField(blank=True, null=True)),
                ('merge_brief', models.TextField(blank=True, null=True)),
                ('content_merged', models.BooleanField(default=False)),
                ('internal_links_updated', models.IntegerField(default=0)),
                ('keyword_reassigned', models.BooleanField(default=False)),
                ('previous_keyword_owner', models.CharField(blank=True, max_length=2048, null=True)),
                ('new_keyword_owner', models.CharField(blank=True, max_length=2048, null=True)),
                ('recommended_by', models.CharField(default='siloq', max_length=30)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conflict_resolutions',
            },
        ),

        # ─────────────────────────────────────────────────────
        # NEW TABLES: Content Lifecycle
        # ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='ContentHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=2048)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('health_score', models.IntegerField()),
                ('health_status', models.CharField(max_length=20)),
                ('impressions_score', models.IntegerField(default=0)),
                ('clicks_score', models.IntegerField(default=0)),
                ('position_score', models.IntegerField(default=0)),
                ('freshness_score', models.IntegerField(default=0)),
                ('backlink_score', models.IntegerField(default=0)),
                ('internal_link_score', models.IntegerField(default=0)),
                ('gsc_impressions', models.IntegerField(default=0)),
                ('gsc_clicks', models.IntegerField(default=0)),
                ('gsc_avg_position', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('days_since_modified', models.IntegerField(default=0)),
                ('backlink_count', models.IntegerField(default=0)),
                ('internal_links_in', models.IntegerField(default=0)),
                ('recommended_action', models.CharField(blank=True, max_length=30, null=True)),
                ('recommended_action_reason', models.TextField(blank=True, null=True)),
                ('redirect_target_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('scoring_period_start', models.DateField(blank=True, null=True)),
                ('scoring_period_end', models.DateField(blank=True, null=True)),
                ('previous_score', models.IntegerField(blank=True, null=True)),
                ('score_change', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_health_scores',
            },
        ),
        migrations.CreateModel(
            name='FreshnessAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=2048)),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('page_type', models.CharField(blank=True, max_length=30, null=True)),
                ('alert_level', models.CharField(max_length=20)),
                ('days_since_modified', models.IntegerField()),
                ('staleness_threshold', models.IntegerField()),
                ('alert_message', models.TextField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('has_traffic', models.BooleanField(default=False)),
                ('gsc_clicks_28d', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'freshness_alerts',
            },
        ),
        migrations.CreateModel(
            name='LifecycleQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=5)),
                ('source_type', models.CharField(max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('primary_page_url', models.CharField(max_length=2048)),
                ('secondary_page_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('recommendation_summary', models.TextField()),
                ('recommendation_detail', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_steps', models.JSONField(blank=True, null=True)),
                ('execution_errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lifecycle_queue',
            },
        ),
        migrations.CreateModel(
            name='ContentAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages_audited', models.IntegerField(default=0)),
                ('pages_healthy', models.IntegerField(default=0)),
                ('pages_refresh', models.IntegerField(default=0)),
                ('pages_monitor', models.IntegerField(default=0)),
                ('pages_kill', models.IntegerField(default=0)),
                ('new_conflicts_found', models.IntegerField(default=0)),
                ('conflicts_resolved_since_last', models.IntegerField(default=0)),
                ('queue_items_created', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_audit_log',
            },
        ),

        # ─────────────────────────────────────────────────────
        # NEW TABLE: Validation & Preflight
        # ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_title', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_slug', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_h1', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('proposed_page_type', models.CharField(blank=True, max_length=30, null=True)),
                ('overall_status', models.CharField(max_length=10)),
                ('blocking_check', models.CharField(blank=True, max_length=50, null=True)),
                ('check_results', models.JSONField(default=dict)),
                ('user_action', models.CharField(blank=True, max_length=30, null=True)),
                ('user_acknowledged_warnings', models.BooleanField(default=False)),
                ('validation_source', models.CharField(default='generation', max_length=30)),
                ('triggered_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_log',
            },
        ),

        # ─────────────────────────────────────────────────────
        # KEYWORD ASSIGNMENT: Remove old indexes/constraints,
        # alter fields, add new fields, then re-add indexes
        # ─────────────────────────────────────────────────────

        # Remove old indexes that reference columns being dropped
        migrations.RemoveIndex(
            model_name='keywordassignment',
            name='keyword_ass_page_id_e149c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordassignment',
            name='keyword_ass_silo_id_1e32aa_idx',
        ),
        # Update unique_together (site_id → site, same effect but cleaner)
        migrations.AlterUniqueTogether(
            name='keywordassignment',
            unique_together={('keyword', 'site')},
        ),

        # Change PK from BigAutoField to UUIDField
        # Safe because 0006 just created this table and deployment failed,
        # so no production data exists.
        migrations.AlterField(
            model_name='keywordassignment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # Alter existing fields to match v2 schema
        migrations.AlterField(
            model_name='keywordassignment',
            name='keyword',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='keywordassignment',
            name='page_type',
            field=models.CharField(default='spoke', max_length=30),
        ),
        migrations.AlterField(
            model_name='keywordassignment',
            name='assignment_source',
            field=models.CharField(default='auto', max_length=30),
        ),
        migrations.AlterField(
            model_name='keywordassignment',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),

        # Add new fields
        migrations.AddField(
            model_name='keywordassignment',
            name='page_url',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='keyword_type',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='gsc_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='gsc_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='gsc_avg_position',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='gsc_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # ─────────────────────────────────────────────────────
        # FK FIELDS: Wire up all ForeignKeys on new tables
        # ─────────────────────────────────────────────────────
        migrations.AddField(
            model_name='silodefinition',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silo_definitions', to='sites.site'),
        ),
        migrations.AddField(
            model_name='silokeyword',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='seo.silodefinition'),
        ),
        migrations.AddField(
            model_name='silokeyword',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silo_keywords', to='sites.site'),
        ),
        migrations.AddField(
            model_name='keywordassignment',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_assignments', to='seo.silodefinition'),
        ),
        migrations.AddField(
            model_name='keywordassignmenthistory',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='seo.keywordassignment'),
        ),
        migrations.AddField(
            model_name='keywordassignmenthistory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_assignment_history', to='sites.site'),
        ),
        migrations.AddField(
            model_name='pagemetadata',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_metadata', to='sites.site'),
        ),
        migrations.AddField(
            model_name='pagemetadata',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_metadata', to='seo.silodefinition'),
        ),
        migrations.AddField(
            model_name='cannibalizationconflict',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cannibalization_conflicts', to='sites.site'),
        ),
        migrations.AddField(
            model_name='conflictpage',
            name='conflict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='seo.cannibalizationconflict'),
        ),
        migrations.AddField(
            model_name='redirectregistry',
            name='conflict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirects', to='seo.cannibalizationconflict'),
        ),
        migrations.AddField(
            model_name='redirectregistry',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='sites.site'),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='conflict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='seo.cannibalizationconflict'),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_resolutions', to='sites.site'),
        ),
        migrations.AddField(
            model_name='conflictresolution',
            name='redirect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_resolutions', to='seo.redirectregistry'),
        ),
        migrations.AddField(
            model_name='contenthealthscore',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_health_scores', to='sites.site'),
        ),
        migrations.AddField(
            model_name='freshnessalert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freshness_alerts', to='sites.site'),
        ),
        migrations.AddField(
            model_name='lifecyclequeue',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_queue', to='sites.site'),
        ),
        migrations.AddField(
            model_name='contentauditlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_audit_logs', to='sites.site'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='proposed_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='seo.silodefinition'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='sites.site'),
        ),

        # ─────────────────────────────────────────────────────
        # KEYWORD ASSIGNMENT: Remove old fields (after new silo FK added)
        # ─────────────────────────────────────────────────────
        migrations.RemoveField(
            model_name='keywordassignment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='keywordassignment',
            name='reassigned_at',
        ),
        migrations.RemoveField(
            model_name='keywordassignment',
            name='reassigned_from_page',
        ),
        migrations.RemoveField(
            model_name='keywordassignment',
            name='silo_id',
        ),

        # ─────────────────────────────────────────────────────
        # INDEXES & CONSTRAINTS
        # ─────────────────────────────────────────────────────

        # KeywordAssignment indexes
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['site'], name='keyword_ass_site_id_322b18_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['silo'], name='keyword_ass_silo_id_1e32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['site', 'page_url'], name='keyword_ass_site_id_876cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignment',
            index=models.Index(fields=['site', 'page_type'], name='keyword_ass_site_id_b3fe31_idx'),
        ),

        # SiloDefinition
        migrations.AddIndex(
            model_name='silodefinition',
            index=models.Index(fields=['site'], name='silo_defini_site_id_71dfca_idx'),
        ),
        migrations.AddIndex(
            model_name='silodefinition',
            index=models.Index(fields=['site', 'status'], name='silo_defini_site_id_f94b65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='silodefinition',
            unique_together={('site', 'slug')},
        ),

        # SiloKeyword
        migrations.AddIndex(
            model_name='silokeyword',
            index=models.Index(fields=['silo'], name='silo_keywor_silo_id_ef13c1_idx'),
        ),
        migrations.AddIndex(
            model_name='silokeyword',
            index=models.Index(fields=['site'], name='silo_keywor_site_id_57a136_idx'),
        ),
        migrations.AddIndex(
            model_name='silokeyword',
            index=models.Index(fields=['keyword'], name='silo_keywor_keyword_64030d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='silokeyword',
            unique_together={('silo', 'keyword')},
        ),

        # KeywordAssignmentHistory
        migrations.AddIndex(
            model_name='keywordassignmenthistory',
            index=models.Index(fields=['assignment'], name='keyword_ass_assignm_a45013_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignmenthistory',
            index=models.Index(fields=['site'], name='keyword_ass_site_id_09033b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordassignmenthistory',
            index=models.Index(fields=['keyword'], name='keyword_ass_keyword_73d9d9_idx'),
        ),

        # PageMetadata
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['site'], name='page_metada_site_id_ea6ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['page_url'], name='page_metada_page_ur_33b624_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['site', 'is_indexable'], name='page_metada_site_id_43d033_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['site', 'http_status'], name='page_metada_site_id_32dcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['silo'], name='page_metada_silo_id_b926b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['site', 'post_type'], name='page_metada_site_id_d65879_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemetadata',
            index=models.Index(fields=['site', 'taxonomy'], name='page_metada_site_id_82cd91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagemetadata',
            unique_together={('site', 'page_url')},
        ),

        # CannibalizationConflict
        migrations.AddIndex(
            model_name='cannibalizationconflict',
            index=models.Index(fields=['site'], name='cannibaliza_site_id_787e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='cannibalizationconflict',
            index=models.Index(fields=['site', 'status'], name='cannibaliza_site_id_8c6ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='cannibalizationconflict',
            index=models.Index(fields=['site', 'severity'], name='cannibaliza_site_id_00d42a_idx'),
        ),
        migrations.AddIndex(
            model_name='cannibalizationconflict',
            index=models.Index(fields=['keyword'], name='cannibaliza_keyword_8e7e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='cannibalizationconflict',
            index=models.Index(fields=['detected_at'], name='cannibaliza_detecte_5c0ff0_idx'),
        ),

        # ConflictPage
        migrations.AddIndex(
            model_name='conflictpage',
            index=models.Index(fields=['conflict'], name='conflict_pa_conflic_62447b_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictpage',
            index=models.Index(fields=['page_url'], name='conflict_pa_page_ur_7145e0_idx'),
        ),

        # RedirectRegistry
        migrations.AddIndex(
            model_name='redirectregistry',
            index=models.Index(fields=['site'], name='redirect_re_site_id_3937a1_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectregistry',
            index=models.Index(fields=['source_url'], name='redirect_re_source__649ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectregistry',
            index=models.Index(fields=['target_url'], name='redirect_re_target__cc5bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectregistry',
            index=models.Index(fields=['site', 'status'], name='redirect_re_site_id_1bd62d_idx'),
        ),
        migrations.AddIndex(
            model_name='redirectregistry',
            index=models.Index(fields=['site', 'reason'], name='redirect_re_site_id_067c42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='redirectregistry',
            unique_together={('site', 'source_url')},
        ),

        # ConflictResolution
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['conflict'], name='conflict_re_conflic_9c18ba_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['site'], name='conflict_re_site_id_6ca0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['action_type'], name='conflict_re_action__c07333_idx'),
        ),

        # ContentHealthScore
        migrations.AddIndex(
            model_name='contenthealthscore',
            index=models.Index(fields=['site'], name='content_hea_site_id_a1426c_idx'),
        ),
        migrations.AddIndex(
            model_name='contenthealthscore',
            index=models.Index(fields=['page_url'], name='content_hea_page_ur_3fc31e_idx'),
        ),
        migrations.AddIndex(
            model_name='contenthealthscore',
            index=models.Index(fields=['site', 'health_status'], name='content_hea_site_id_0952ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contenthealthscore',
            index=models.Index(fields=['scored_at'], name='content_hea_scored__74b89d_idx'),
        ),
        migrations.AddIndex(
            model_name='contenthealthscore',
            index=models.Index(fields=['site', 'recommended_action'], name='content_hea_site_id_e972a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contenthealthscore',
            unique_together={('site', 'page_url', 'scored_at')},
        ),

        # FreshnessAlert
        migrations.AddIndex(
            model_name='freshnessalert',
            index=models.Index(fields=['site'], name='freshness_a_site_id_e134fc_idx'),
        ),
        migrations.AddIndex(
            model_name='freshnessalert',
            index=models.Index(fields=['site', 'status'], name='freshness_a_site_id_571444_idx'),
        ),
        migrations.AddIndex(
            model_name='freshnessalert',
            index=models.Index(fields=['site', 'alert_level'], name='freshness_a_site_id_6556ad_idx'),
        ),

        # LifecycleQueue
        migrations.AddIndex(
            model_name='lifecyclequeue',
            index=models.Index(fields=['site'], name='lifecycle_q_site_id_521436_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecyclequeue',
            index=models.Index(fields=['site', 'status'], name='lifecycle_q_site_id_fee693_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecyclequeue',
            index=models.Index(fields=['site', 'priority'], name='lifecycle_q_site_id_acca03_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecyclequeue',
            index=models.Index(fields=['site', 'action_type'], name='lifecycle_q_site_id_fb3d69_idx'),
        ),

        # ContentAuditLog
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['site'], name='content_aud_site_id_71cd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['audit_type'], name='content_aud_audit_t_8c9f42_idx'),
        ),

        # ValidationLog
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['site'], name='validation__site_id_84164a_idx'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['overall_status'], name='validation__overall_0560e0_idx'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['proposed_keyword'], name='validation__propose_186a80_idx'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['created_at'], name='validation__created_6bfd85_idx'),
        ),
    ]
