# Generated by Django 5.0.1 on 2026-02-15 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_anti_cannibalization_engine_15_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchortextconflict',
            name='anchor_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anchortextconflict',
            name='anchor_text_normalized',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anchortextconflict',
            name='conflicting_pages',
            field=models.ManyToManyField(related_name='anchor_conflicts', to='seo.page'),
        ),
        migrations.AlterField(
            model_name='anchortextconflict',
            name='occurrence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='anchor_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='anchor_text_normalized',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='context_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='is_in_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='is_nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='source_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='seo.page'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='target_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='seo.page'),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='target_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_money_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent_silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_pages', to='seo.page'),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='external_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='h2_texts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='h3_texts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='internal_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='issues',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='seodata',
            name='seo_score',
            field=models.IntegerField(default=0),
        ),
    ]
